name: test

on:

  workflow_dispatch:
    inputs:
      runs-on:
        description: 'GitHub runner label'
        type: choice
        default: ubuntu-latest
        required: false
        options:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11
        - windows-2022
      mpi:
        description: 'MPI implementation name'
        type: choice
        default: ''
        required: false
        options:
        - mpich
        - openmpi
        - msmpi

  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
        required: false
      mpi:
        type: string
        default: ''
        required: false

jobs:

  test:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"

    steps:

    - name: Configure hostname
      if:   runner.os == 'Linux' || runner.os == 'macOS'
      run:  echo 127.0.0.1 `hostname` | sudo tee -a /etc/hosts > /dev/null

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MPI (${{ inputs.mpi }})
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ inputs.mpi }}

    - name: Use Python ${{ matrix.py }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
        architecture: x64

    - name: Install packaging tools
      run:  python -m pip install --upgrade setuptools pip wheel
    - name: Install build dependencies
      run:  python -m pip install --upgrade cython
    - name: Build package
      run:  python -m pip wheel -vvv --wheel-dir=dist .
    - name: Upload package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mpi4py-${{inputs.runs-on}}-${{inputs.mpi}}
        path: dist/mpi4py-*.whl

    - name: Install test dependencies
      run:  python -m pip install --upgrade -r conf/requirements-test.txt
      if:   ${{ runner.os == 'Linux' || !startsWith(matrix.py, 'pypy-') }}
    - name: Install package for testing
      run:  python -m pip install --no-index --find-links=dist mpi4py
    - name: Test package
      run:  mpiexec -n 1 python test/runtests.py -v
    - name: Test package
      run:  mpiexec -n 2 python test/runtests.py -v -f -e spawn
    - name: Test subpackage
      run:  mpiexec -n 1 python demo/futures/test_futures.py -v
    - name: Test subpackage
      run:  mpiexec -n 2 python demo/futures/test_futures.py -v
    - name: Test subpackage
      run:  python demo/test-run/test_run.py -v
    - name: Uninstall package after testing
      run:  python -m pip uninstall --yes mpi4py
